name: integration

on:
  push:

jobs:
  basics:
    runs-on: ubuntu-latest

    steps:
    - name: git clone
      uses: actions/checkout@v2

  # Always check all markdown files in the repo since some links may got broken since last check
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
